### ISSUE TITLE
Traceback when lsb_release is not installed

### ISSUE THREAD

**Issue by xsuchy** [nir0s/distro#140]
I got this:

```
$ python
Python 2.7.12 (default, Aug  9 2016, 15:48:18) 
[GCC 6.1.1 20160621 (Red Hat 6.1.1-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import dist
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named dist
>>> import distro
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/distro.py", line 1052, in <module>
    _distro = LinuxDistribution()
  File "/usr/lib/python2.7/site-packages/distro.py", line 595, in __init__
    if include_lsb else {}
  File "/usr/lib/python2.7/site-packages/distro.py", line 923, in _lsb_release_info
    stdout, stderr = stdout.decode('ascii'), stderr.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 23: ordinal not in range(128)
>>> 
msuchy@unused-4-202:~/packaging/python-dist$ lsb_release -a
bash: lsb_release: příkaz nenalezen
```

This is due missing /usr/bin/lsb_release on my system (should not cause traceback) and because "Command not found" is localized to "příkaz nenalezen" which have unicode characters. You should either assume UTF8, or start it with LC_ALL=C.

**Comment by nir0s** [comment]
Thank you! Would you like to contribute the fix?
